---
title: "Heritability of >2,000 traits & disorders in UK Biobank"
output: html_document
---

<br>

<div class="well">

As you may know, the UK Biobank recently released data on ~500,000 individuals to the scientific community to advance research on genetics. The [Neale Lab](http://nealelab.is) has been working to make some basic analyses of that data freely available; you can read more about the overall effort [here](http://www.nealelab.is/blog/2017/7/19/rapid-gwas-of-thousands-of-phenotypes-for-370000-samples-in-the-uk-biobank).

<br>

Building on the initial genome-wide association analyses, we’ve now estimated the heritability of each of those traits and disorders, over 2,000 as of this writing. As with the primary analyses, we’re making the heritability results available for [browsing](h2_browser.html) and bulk <a href="https://www.dropbox.com/sh/g28ee03vy4hvqw5/AADAkDbSFHsYE8bme1Jjeekca/ldsc_results?dl=0" onclick="trackOutboundLink('https://www.dropbox.com/sh/g28ee03vy4hvqw5/AADAkDbSFHsYE8bme1Jjeekca/ldsc_results?dl=0'); return false;">download</a>. 

<br>

<a href="h2_browser.html" class="btn btn-primary btn-lg">Browse  $h^2$</a>
<a href="plots_home.html" class="btn btn-primary btn-lg">Explore Plots</a>
<a href="https://www.dropbox.com/sh/g28ee03vy4hvqw5/AADAkDbSFHsYE8bme1Jjeekca/ldsc_results?dl=0"  class="btn btn-primary btn-lg" onclick="trackOutboundLink('https://www.dropbox.com/sh/g28ee03vy4hvqw5/AADAkDbSFHsYE8bme1Jjeekca/ldsc_results?dl=0'); return false;">Download Results</a>

<br>

You can learn more about the heritability analysis in this series of blog posts:

* [Heritability 101: What is “heritability”?](http://www.nealelab.is/blog/2017/9/13/heritability-101-what-is-heritability)
* [Heritability 201: Types of heritability and how we estimate it](http://www.nealelab.is/blog/2017/9/13/heritability-201-types-of-heritability-and-how-we-estimate-it)
* (coming soon) Insights from estimates of SNP-heritability for >2,000 traits and disorders in UK Biobank

<br>

More technical descriptions are also available:

* [Heritability 501: LDSR-based h2 in UKBB for the technically-minded](http://www.nealelab.is/blog/2017/9/14/heritability-501-ldsr-based-h2-in-ukbb-for-the-technically-minded)
* [UKBB_ldsc github repository](https://github.com/Nealelab/UKBB_ldsc)

<br>

We view these results as preliminary and subject to change as we continue to refine the analyses as well as the genome-wide association results they are based on. But we hope you’ll agree that they provide an interesting and useful first look at the genetics of the many diverse traits and disorders studied in the UK Biobank.

<br>

If you want more information, please **contact us at: <nealelab.ukb@gmail.com>.**

</div>

<br>
<br>

<div class="well">

#### FAQ

**Where can I find the heritability results?**

We’ve created a browser to explore the results [here](h2_browser.html). You can also download the full results file <a href="https://www.dropbox.com/sh/g28ee03vy4hvqw5/AADAkDbSFHsYE8bme1Jjeekca/ldsc_results?dl=0" onclick="trackOutboundLink('https://www.dropbox.com/sh/g28ee03vy4hvqw5/AADAkDbSFHsYE8bme1Jjeekca/ldsc_results?dl=0'); return false;">here</a>.

<br>

**What method have you used to estimated heritability?**

To enable this quick initial analysis on such large-scale data we’re relying on LD score regression ([article](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4495769/), [github repo](https://github.com/bulik/ldsc)). Full code and technical details are available in the [UKBB_ldsc github repository](https://github.com/Nealelab/UKBB_ldsc) and described in [Heritability 501](http://www.nealelab.is/blog/2017/9/14/heritability-501-ldsr-based-h2-in-ukbb-for-the-technically-minded).

<br>

**Are the primary GWAS results used for this analysis available? **

Yes! Results will be available for browsing through the [Global Biobank Engine](https://biobankengine.stanford.edu/), and the full GWAS results are [available for download](https://sites.google.com/broadinstitute.org/ukbbgwasresults/). See [the introductory post](http://www.nealelab.is/blog/2017/7/19/rapid-gwas-of-thousands-of-phenotypes-for-370000-samples-in-the-uk-biobank) for much more information. 

<br>

**How should I interpret these heritability results?**

*Very carefully.* For starters, we’ve written a couple of primers that cover the concept of heritability and common misconceptions ([Heritability 101](http://www.nealelab.is/blog/2017/9/13/heritability-101-what-is-heritability)) and the specific type of heritability that’s being estimated in this analysis ([Heritability 201](http://www.nealelab.is/blog/2017/9/13/heritability-201-types-of-heritability-and-how-we-estimate-it)). A longer discussion of the many limitations of this analysis is included in our more technical description of the project ([Heritability 501](http://www.nealelab.is/blog/2017/9/14/heritability-501-ldsr-based-h2-in-ukbb-for-the-technically-minded)).

We’ll revisit this question in future posts as we explore the results in more detail, but here’s the executive summary: This is a very rough initial analysis and should be treated accordingly. All estimates are for (a) the heritability from common genetic variants (b) of automatically cleaned and transformed phenotypes (c) in a non-random population sample of the UK (d) estimated with a fairly simple statistical model. We expect the results will mostly be useful for generating hypotheses for follow-up (e.g. identifying trends in the estimates for categories of phenotypes, choosing phenotypes with robust statistical evidence for heritability), rather than being a definitive statement about the “true” heritability of a individual phenotype. 

</div>

<br>
<br>

<div class="well">

#### Credits

**Heritability analysis team:**
Liam Abbott,
Sam Bryant,
Claire Churchhouse,
Benjamin Neale,
Duncan Palmer,
Raymond Walters

**Neale Lab UKBB team:**
Liam Abbott,
Verneri Anttila,
Krishna Aragam,
Jon Bloom,
Sam Bryant,
Claire Churchhouse,
Joanne Cole,
Mark J. Daly,
Andrea Ganna,
Jackie Goldstein,
Mary Haas,
Joel Hirschhorn,
Daniel Howrigan,
Sekar Kathiresan,
Dan King,
Benjamin Neale,
Duncan Palmer,
Tim Poterba,
Manuel Rivas,
Cotton Seed,
Sailaja Vedantam,
Raymond Walters

</div>
