---
title: "Results Files for LDSR of UK Biobank GWAS"
date: "Last updated `r format(Sys.Date())`"
author: "Results from the [Neale Lab](credits.html)"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: false
    toc_depth: 3
---

```{r child = '_toc_fix.Rmd'}
```

<br>

<div class="well">

### Heritability Results

Results files for this LDSR analysis are available <a href="https://www.dropbox.com/sh/i4kcffb5ilsktyg/AABYP5Xyg_w6Yw8RrLnYwbsLa?dl=0" onclick="trackOutboundLink('https://www.dropbox.com/sh/i4kcffb5ilsktyg/AABYP5Xyg_w6Yw8RrLnYwbsLa?dl=0'); return false;">on Dropbox</a>. Direct download links for each file are below.

| File | Size | Description |
|--------|------|----------------------------------------------------|
| <a href="https://www.dropbox.com/s/8vca84rsslgbsua/ukb31063_h2_topline.02Oct2019.tsv.gz?dl=1" onclick="trackOutboundLink('https://www.dropbox.com/s/8vca84rsslgbsua/ukb31063_h2_topline.02Oct2019.tsv.gz?dl=1'); return false;">`ukb31063_h2_topline.02Oct2019.tsv.gz`</a> | 681 KB | Primary SNP heritability results for each phenotype, as reported in the [browser](h2_browser.html) |
| <a href="https://www.dropbox.com/s/gu9ueqdulze9c9x/ukb31063_h2_z4.02Oct2019.tsv.gz?dl=1" onclick="trackOutboundLink('https://www.dropbox.com/s/gu9ueqdulze9c9x/ukb31063_h2_z4.02Oct2019.tsv.gz?dl=1'); return false;">`ukb31063_h2_z4.02Oct2019.tsv.gz`</a> | 4.4 MB | Partitioned heritability results for all primary phenotypes reaching $z>4$ for significance of $h^2_g$ |
| <a href="https://www.dropbox.com/s/ipeqyhrpdqav5uh/ukb31063_h2_all.02Oct2019.tsv.gz?dl=1" onclick="trackOutboundLink('https://www.dropbox.com/s/ipeqyhrpdqav5uh/ukb31063_h2_all.02Oct2019.tsv.gz?dl=1'); return false;">`ukb31063_h2_all.02Oct2019.tsv.gz`</a> | 73.7 MB | LDSR results for all of the UKB Neale Lab GWAS, including partitioning, sex-stratified results, and alternative versions of phenotypes (e.g. biomarker dilution, non-normalized) |

Note the first two files are simply a subset of the full results in `ukb31063_h2_all.02Oct2019.tsv.gz`. They are provided for the convenience of a smaller download.

<p></p>

### LDSC Sumstat Files

In addition to the LDSR results, the exported sumstat files in LDSC format are also available [on Dropbox](). A manifest for easier programatic access is available [here](). 

These files are provided to facilitate running your own LDSR SNP heritability analyses with different models or for genetic correlation analyses. For genetic correlations between the heritable phenotypes in this UKB GWAS, visit [ukbb-rg.hail.is](https://ukbb-rg.hail.is/)

<p></p>

### Reference Files

LD scores, weights, and allele frequencies for the Baseline-LD v1.1 model used here are available for [download from the Alkes Price lab](https://data.broadinstitute.org/alkesgroup/LDSCORE/).

<p></p>

### Full GWAS Results

The full GWAS results are available for download from Dropbox. A full manifest of the available files, with links and documentation, are available [here](https://docs.google.com/spreadsheets/d/1kvPoupSzsSFBNSztMzl04xMoSC3Kcx3CrjVf4yBmESU/edit#gid=227859291). 

For more information about the GWAS analyses, see [the Neale Lab blog](http://www.nealelab.is/uk-biobank) and [github](https://github.com/Nealelab/UK_Biobank_GWAS). 

<p></p>

### Previous SNP Heritability Results

Lastly, the previous results based on the Round 1 Neale Lab GWAS remain available for download <a href="https://www.dropbox.com/sh/g28ee03vy4hvqw5/AADAkDbSFHsYE8bme1Jjeekca/ldsc_results?dl=0" onclick="trackOutboundLink('https://www.dropbox.com/sh/g28ee03vy4hvqw5/AADAkDbSFHsYE8bme1Jjeekca/ldsc_results?dl=0'); return false;">on Dropbox</a>, including both univariate and paritioned LDSR results. Round 1 LDSR results can be browsed [here](round1_h2_browser.html) (with the corresponding univariate results [here](round1_h2_univar_browser.html)).

</div>
