---
title: "UKBB SNP-Heritability Browser"
date: "Last updated `r format(Sys.Date())`"
output: html_document
params:
  isUnivar: FALSE
  datfile: "ukb31063_h2_topline.17jun2019.tsv.gz"
---

<style type="text/css">
div.main-container {
  max-width: 1800px;
  margin-left: 50px;
  margin-right: 50px;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# table {
#   table-layout:fixed;
# }
# table td {
#   word-wrap: break-word;
#   max-width: 300px;
#   white-space: pre-wrap;
# }

# parameters
dat <- read.delim(file=normalizePath(params$datfile),sep='\t',header=T,stringsAsFactors=F,colClasses=c(intercept_p="character"))
isUnivar <- as.logical(params$isUnivar)

# packages
require(reshape2)
require(ggplot2)
require(plotly)
require(DT)
require(crosstalk)
require(crosstool)

# setup links
dat$description <- paste0("<a href='h2_summary_",dat$phenotype,".html'>",dat$description,"</a>")
```

<br>

`r if(isUnivar){paste0("<div class=\"panel panel-warning\"><div class=\"panel-heading\"><h3 class=\"panel-title\">Note</h3></div><div class=\"panel-body\">You are viewing results from univariate LD score regression. We recommend the <a href=\"h2_browser.html\">partitioned results</a> instead.</div></div>")}`

```{r lookup, echo=FALSE}
# shared_dat <- SharedData$new(dat[, c("phenotype","description","h2_liability","h2_p","h2_sig","confidence","intercept","intercept_p","ratio","n","Neff","isBinary","prevalence","source","sex")])
dat <- dat[,c("phenotype","description","h2_liability","h2_liability_se","h2_p","h2_sig","confidence","notes","intercept","intercept_se","intercept_p","lambdaGC","ratio","Neff","variable_type","prevalence","source","sex")]

# avoid empty values
dat$h2_sig[is.na(dat$h2_sig)] <- "NA"
dat$notes[dat$notes==""] <- "none"

# setup factors
dat$sex[dat$sex=="both_sexes"] <- "both"
fact_cols <- c("h2_sig","confidence","notes","variable_type","source","sex")
for(nam in fact_cols){
  dat[,nam] <- as.factor(dat[,nam])
}

# setup numeric (do here to get shorter length for table formatting)
num_cols <- c("h2_liability","h2_liability_se","intercept_se","ratio","prevalence","lambdaGC")
for(nam in num_cols){
  dat[,nam] <- signif(dat[,nam],3)
}

# avoid p=1
p_cols <- c("h2_p")
for(nam in p_cols){
  prec <- 3
  p_num <- signif(dat[,nam],prec)
  while(any(p_num==1)){
    prec <- prec+1
    p_num[p_num==1] <- signif(dat[,nam],prec)[p_num==1]
  }
  dat[,nam] <- p_num
}

# handle intercept_p as a string (due to high precision p-vals)
prec <- 3
intp_string <- dat$intercept_p
intp_string[(dat$intercept_p == as.character(as.numeric(dat$intercept_p)))] <- as.character(signif(as.numeric(dat$intercept_p),prec)[(dat$intercept_p == as.character(as.numeric(dat$intercept_p)))])
highstr <- intp_string[!(dat$intercept_p == as.character(as.numeric(dat$intercept_p)))]
highstr_lead <- as.character(signif(as.numeric(substr(highstr,1,6)),prec))
highstr_exp <- sapply(highstr,function(a) strsplit(a,split="e")[[1]][2],USE.NAMES = F)
intp_string[!(dat$intercept_p == as.character(as.numeric(dat$intercept_p)))] <- paste0(highstr_lead,"e",highstr_exp)
while(any(intp_string=="1")){
  prec <- prec+1
  intp_string[intp_string=="1"] <- as.character(signif(as.numeric(dat$intercept_p),prec)[intp_string=="1"])
}
dat$intercept_p <- intp_string

# extra num precision
num_cols4 <- c("intercept")
for(nam in num_cols4){
  dat[,nam] <- signif(dat[,nam],4)
}

# integers
int_cols <- c("Neff")
for(nam in int_cols){
  dat[,nam] <- as.integer(round(dat[,nam]))
}

dt <- datatable(SharedData$new(dat), 
      filter = "top",
		  rownames = F, 
		  colnames = c("ID","Phenotype","h2","h2 se","h2 p","h2 Sig?","Confidence","Notes","Int.","Int. se","Int. p","lambda","ratio","Neff","var type","Prev.","Source","Sex"), 
		  selection="none",
		  style="default", 
		  class="display", 
		  escape=F,
      extensions = c('FixedHeader','Buttons'),
		  options = list(scrollY="475px", scrollX=TRUE, pageLength=12, fixedHeader=TRUE, autoWidth=TRUE,
		                 order = list(list(4,"asc"), list(6, "asc")),
		                 columnDefs = list(list(visible=FALSE, targets=c(0,3,7,9,11:12,14:15,17)),
		                                   list(width="300px", targets=c(1)),
		                                   list(className='dt-right', targets=c(10)),
		                                   list(className='dt-center', targets=c(5,6)),
		                                   # ordering on SE(int) in order to get int p-vals < 1e-300 to sort correctly
		                                   # not a robust solution (vs. sorting on z score), but works for now
		                                   # without adding a column of data to the file size
		                                   list(orderData=c(10,9), targets=c(10)),
		                                   list(orderSequence=c("desc","asc"), targets=c(2,8))),
		                 dom = 'Bfrtip', buttons = I('colvis'),
		                 buttons = list(list(extend = 'colvis', columns = c(1)))) 
) 

dt
```

<br>
