---
title: "Vizualizing $h^2$ results: QQ plots"
date: "Last updated `r format(Sys.Date())`"
author: "Results from the [Neale Lab](credits.html)"
output: 
  html_document:
    toc: true
    toc_float: true
params:
  datfile: "../results/ukbb_h2part.RData"
---

```{r child = '_toc_fix.Rmd'}
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(reshape2)
require(ggplot2)
require(plotly)
require(DT)
require(crosstalk)
require(crosstool)

# handle params
load(file=params$datfile)

# setup
dat$isBinary <- !is.na(dat$N_case)
dat$Neff <- dat$N
dat$Neff[dat$isBinary] <- round( (4/((1/dat$N_case)+(1/dat$N_control)))[dat$isBinary], 2)

dat <- dat[dat$Neff > 200,]

dat$isNomSig_h2 <- dat$h2_p < .05
dat$isBonfSig_h2 <- dat$h2_p < (.05/nrow(dat))
dat$isNomSig_int <- dat$intercept_p < .05
dat$isBonfSig_int <- dat$intercept_p < (.05/nrow(dat))
dat$table_desc <- paste0("<a href='h2_summary_",dat$phenotype,".html'>",dat$description,"</a>")

# shared data object
d3 <- dat[,c("phenotype","table_desc","description","prevelence","Neff","isBinary","isBonfSig_h2","isBonfSig_int","intercept","h2_liability","intercept_p","h2_p","Coding_UCSC..Coefficient_p","Conserved_LindbladToh..Coefficient_p","CTCF_Hoffman..Coefficient_p","DGF_ENCODE..Coefficient_p","DHS_peaks_Trynka..Coefficient_p","DHS_Trynka..Coefficient_p","Enhancer_Andersson..Coefficient_p","Enhancer_Hoffman..Coefficient_p","FetalDHS_Trynka..Coefficient_p","H3K27ac_Hnisz..Coefficient_p","H3K27ac_PGC2..Coefficient_p","H3K4me1_peaks_Trynka..Coefficient_p","H3K4me1_Trynka..Coefficient_p","H3K4me3_peaks_Trynka..Coefficient_p","H3K4me3_Trynka..Coefficient_p","H3K9ac_peaks_Trynka..Coefficient_p","H3K9ac_Trynka..Coefficient_p","Intron_UCSC..Coefficient_p","PromoterFlanking_Hoffman..Coefficient_p","Promoter_UCSC..Coefficient_p","Repressed_Hoffman..Coefficient_p","SuperEnhancer_Hnisz..Coefficient_p","TFBS_ENCODE..Coefficient_p","Transcr_Hoffman..Coefficient_p","TSS_Hoffman..Coefficient_p","UTR_3_UCSC..Coefficient_p","UTR_5_UCSC..Coefficient_p","WeakEnhancer_Hoffman..Coefficient_p","Super_Enhancer_Vahedi..Coefficient_p","Typical_Enhancer_Vahedi..Coefficient_p","GERP.NS..Coefficient_p","GERP.RSsup4..Coefficient_p","MAF_Adj_Predicted_Allele_Age..Coefficient_p","MAF_Adj_LLD_AFR..Coefficient_p","Recomb_Rate_10kb..Coefficient_p","Nucleotide_Diversity_10kb..Coefficient_p","Backgrd_Selection_Stat..Coefficient_p","CpG_Content_50kb..Coefficient_p")]

```

<br>

### P-value of $h^2$ (one-tailed)

<div class="well">

```{r qq_h2, echo=FALSE}

exp_nlogp <- function(p){
	nn <- length(p)
	qquad <- 1:nn
	qref <- (qquad-.5)/nn
	idx <- rank(p)
	return(-log10(qref[idx]))
}

qquad <-c(1:nrow(d3))
qref <- ((qquad-.5)/nrow(d3))
ci_up <- qbeta(.975,qquad,nrow(d3)+1-qquad)
ci_lo <- qbeta(.025,qquad,nrow(d3)+1-qquad)

pp <- plot_ly(d3, 
			  x=~exp_nlogp(h2_p), 
			  y=~(-log10(h2_p)),
			  type="scatter",
			  mode="markers",
			  showlegend=F,
			  hoverinfo="text",
			  text = ~paste0(
			  		    "Phenotype: ", description,
			  			"<br>Intercept: ", round(intercept,5), " (p=",signif(intercept_p, 3),")",
			  			"<br>Liability h2: ", round(h2_liability,4), " (p=",signif(h2_p, 3),")",
			  			"<br>Effective N: ", Neff,
			  			"<br>Prevalence: ", prevelence)
	) %>% add_trace(
		x=-log10(qref),
		y=-log10(qref),
		mode="lines",
		showlegend=F,
		hoverinfo = "text",
		text = ""
	) %>% add_trace(
		x=-log10(qref),
		y=-log10(ci_up),
		mode="lines",
		line=list(color='#2ca02c'),
		showlegend=F,
		hoverinfo = "text",
		text = ""
	) %>% add_trace(
		x=-log10(qref),
		y=-log10(ci_lo),
		mode="lines",
		line=list(color='#2ca02c'),
		fill="tonexty",
		fillcolor='rgba(44,160,44,0.2)',
		showlegend=F,
		hoverinfo = "text",
		text = ""
	) %>% layout(
	  			 showlegend=F,
	  			 xaxis = list(title="Expected -log10(p-value)"),
	  			 yaxis = list(title="Observed -log10(p-value)")
	  )

bscols(widths=c(12),
	config(pp, collaborate = F, showLink=F, displayModeBar=F, displaylogo=F, sendData=F)
)
```

</div>

<br>

### P-value of intercept (one-tailed)

<div class="well">

```{r qq_int, echo=FALSE}

pp <- plot_ly(d3, 
			  x=~exp_nlogp(intercept_p), 
			  y=~(-log10(intercept_p)),
			  type="scatter",
			  mode="markers",
			  showlegend=F,
			  hoverinfo="text",
			  text = ~paste0(
			  		    "Phenotype: ", description,
			  			"<br>Intercept: ", round(intercept,5), " (p=",signif(intercept_p, 3),")",
			  			"<br>Liability h2: ", round(h2_liability,4), " (p=",signif(h2_p, 3),")",
			  			"<br>Effective N: ", Neff,
			  			"<br>Prevalence: ", prevelence)
	) %>% add_trace(
		x=-log10(qref),
		y=-log10(qref),
		mode="lines",
		showlegend=F,
		hoverinfo = "text",
		text = ""
	) %>% add_trace(
		x=-log10(qref),
		y=-log10(ci_up),
		mode="lines",
		line=list(color='#2ca02c'),
		showlegend=F,
		hoverinfo = "text",
		text = ""
	) %>% add_trace(
		x=-log10(qref),
		y=-log10(ci_lo),
		mode="lines",
		line=list(color='#2ca02c'),
		fill="tonexty",
		fillcolor='rgba(44,160,44,0.2)',
		showlegend=F,
		hoverinfo = "text",
		text = ""
	) %>% layout(
	  			 showlegend=F,
	  			 xaxis = list(title="Expected -log10(p-value)"),
	  			 yaxis = list(title="Observed -log10(p-value)")
	  )

bscols(widths=c(12),
	config(pp, collaborate = F, showLink=F, displayModeBar=F, displaylogo=F, sendData=F)
)
```

</div>

<br>

### P-value for coefficients of partitioned annotation (two-tailed)

<div class="well">

```{r qq_coef, echo=FALSE}

prank <- apply(d3[,13:50],2,rank)
colnames(prank) <- paste0(colnames(prank),"_rank")

d3b <- data.frame(cbind(d3$phenotype,prank))
names(d3b)[1] <- "phenotype"
d3bm <- melt(d3b,c("phenotype"),value.name="rank", variable.name="var1")
d3bm$annot <- as.factor(gsub("..Coefficient_p_rank","",d3bm$var1))

d3m <- melt(d3[,c(1,3,5,9:12,13:50)],c("phenotype","description","h2_liability","h2_p","intercept","intercept_p","Neff"),value.name="pval", variable.name="var2")
d3m$annot <- as.factor(gsub("..Coefficient_p","",d3m$var2))

df <- merge(d3m,d3bm,by=c("phenotype","annot"))


qquad <-c(1:nrow(d3))
qref <- ((qquad-.5)/nrow(d3))
alph <- (.05/2)/length(levels(df$annot))
ci_up <- qbeta(.975,qquad,nrow(d3)+1-qquad)
ci_lo <- qbeta(.025,qquad,nrow(d3)+1-qquad)

exp_p <- function(rr,nn){
	qq <- (as.numeric(rr)-.5)/nn
	return(-log10(qq))
}

df2 <- df[df$pval < .05,]
df2 <- df2[order(df2$annot,decreasing = T),]

pp <- plot_ly(df2, height=600, type="scatter", mode="markers") %>% 
			add_markers(
			  x=~exp_p(rank,nrow(d3)), 
			  y=~(-log10(pval)),
			  split=~annot,
			  mode="markers",
			  hoverinfo="text",
			  text = ~paste0(
			  		    "Phenotype: ", description,
			  			"<br>Annotation: ",annot)
			) %>% add_trace(
		x=-log10(qref),
		y=-log10(qref),
		mode="lines",
		line=list(color='rgba(0,0,0,0.8)'),
		showlegend=F,
		hoverinfo = "text",
		text = ""
	) %>% add_trace(
		x=-log10(qref),
		y=-log10(ci_up),
		mode="lines",
		line=list(color='rgba(0,0,0,0.3)'),
		showlegend=F,
		hoverinfo = "text",
		text = ""
	) %>% add_trace(
		x=-log10(qref),
		y=-log10(ci_lo),
		mode="lines",
		line=list(color='rgba(0,0,0,0.3)'),
		fill="tonexty",
		fillcolor='rgba(0,0,0,0.2)',
		showlegend=F,
		hoverinfo = "text",
		text = ""
	) %>% layout(
	  			 xaxis = list(title="Expected -log10(p-value)"),
	  			 yaxis = list(title="Observed -log10(p-value)")
	  )

bscols(widths=c(12),
	config(pp, collaborate = F, showLink=F, displayModeBar=F, displaylogo=F, sendData=F)
)
```

<br>

**Note:** For efficiency only p-values < .05 are displayed.

</div>

<br>
